<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Lab 8.5 - Prompting Large Language Models

In this lab we will practise prompting with a few Large Language Models (LLMs) using Groq (not to be confused with Grok). Groq is a platform that provides access to their custom-built AI hardware via APIs, allowing users to run open-source models such as Llama.

We shall see that while LLMs are powerful tools, how you ask a question or frame a task can dramatically influence the results obtained.

## Set-up

Step 1: Sign up for a free Groq account at https://console.groq.com/home .

Step 2: Create a new API key at https://console.groq.com/keys. Copy-paste it into an empty text file called 'groq_key.txt'.

Running the next cell will then read in this key and assign it to the variable `groq_key`.

In [1]:
from google.colab import files
uploaded = files.upload()

Saving groq_key.txt to groq_key.txt

In [2]:
groqfilename = r'groq_key.txt' # this file contains a single line containing your Groq API key only
try:
    with open(groqfilename, 'r') as f:
        groq_key = f.read().strip()
except FileNotFoundError:
    print("'%s' file not found" % filename)

In [3]:
!pip install groq

Collecting groq
  Downloading groq-0.28.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.11/dist-packages (from groq) (4.9.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from groq) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from groq) (0.28.1)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.11/dist-packages (from groq) (2.11.7)
Requirement already satisfied: sniffio in /usr/local/lib/python3.11/dist-packages (from groq) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.10 in /usr/local/lib/python3.11/dist-packages (from groq) (4.14.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.11/dist-packages (from anyio<5,>=3.5.0->groq) (3.10)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->groq) (2025.6.15)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx<1,>=0.23.0->groq) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->groq) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->groq) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->groq) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic<3,>=1.9.0->groq) (0.4.1)
Downloading groq-0.28.0-py3-none-any.whl (130 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.2/130.2 kB 3.3 MB/s eta 0:00:00
Installing collected packages: groq
Successfully installed groq-0.28.0

In [4]:
from groq import Groq
import requests
import pandas as pd
from IPython.display import Markdown

First create an instance of the Groq client:

In [5]:
client = Groq(api_key=groq_key)

The following code shows what models are currently accessible through Groq. `context_window` refers to the size of memory (in tokens) during a session and `max_completion_tokens` is the maximum number of tokens that are generated in an output.

In [6]:
url = "https://api.groq.com/openai/v1/models"

headers = {
    "Authorization": f"Bearer {groq_key}",
    "Content-Type": "application/json"
}

response = requests.get(url, headers=headers)

pd.DataFrame(response.json()['data']).sort_values(['created'], ascending=False)

,id,object,created,owned_by,active,context_window,public_apps,max_completion_tokens
7,meta-llama/llama-prompt-guard-2-86m,model,1748632165,Meta,True,512,None,512
13,meta-llama/llama-prompt-guard-2-22m,model,1748632101,Meta,True,512,None,512
20,qwen/qwen3-32b,model,1748396646,Alibaba Cloud,True,131072,None,40960
8,meta-llama/llama-guard-4-12b,model,1746743847,Meta,True,131072,None,1024
21,meta-llama/llama-4-maverick-17b-128e-instruct,model,1743877158,Meta,True,131072,None,8192
4,meta-llama/llama-4-scout-17b-16e-instruct,model,1743874824,Meta,True,131072,None,8192
19,compound-beta-mini,model,1742953279,Groq,True,131072,None,8192
2,qwen-qwq-32b,model,1741214760,Alibaba Cloud,True,131072,None,131072
9,compound-beta,model,1740880017,Groq,True,131072,None,8192
3,playai-tts-arabic,model,1740682783,PlayAI,True,8192,None,8192
15,playai-tts,model,1740682771,PlayAI,True,8192,None,8192
10,mistral-saba-24b,model,1739996492,Mistral AI,True,32768,None,32768
16,deepseek-r1-distill-llama-70b,model,1737924940,DeepSeek / Meta,True,131072,None,131072
5,allam-2-7b,model,1737672203,SDAIA,True,4096,None,4096
11,llama-3.3-70b-versatile,model,1733447754,Meta,True,131072,None,32768
18,whisper-large-v3-turbo,model,1728413088,OpenAI,True,448,None,448
0,whisper-large-v3,model,1693721698,OpenAI,True,448,None,448
1,llama3-70b-8192,model,1693721698,Meta,True,8192,None,8192
12,llama-3.1-8b-instant,model,1693721698,Meta,True,131072,None,131072
6,distil-whisper-large-v3-en,model,1693721698,Hugging Face,True,448,None,448
17,gemma2-9b-it,model,1693721698,Google,True,8192,None,8192
14,llama3-8b-8192,model,1693721698,Meta,True,8192,None,8192

The Groq client object enables interaction with the Groq REST API and a chat completion request is made via the client.chat.completions.create method.

The most important arguments of the client.chat.completions.create method are the following:
* messages: a list of messages (dictionary form) that make up the conversation to date
* model: a string indicating which model to use (see [list of models](https://console.groq.com/docs/models))
* max_completion_tokens: the maximum number of tokens that are generated in the chat completion
* response_format: setting this to `{ "type": "json_object" }` enables JSON output
* seed: sample deterministically as best as possible, though identical outputs each time are not guaranteed
* temperature: between 0 and 2 where higher values like 0.8 make the output more random (creative) and values like 0.2 are more focused and deterministic

In [7]:
help(client.chat.completions.create)

Help on method create in module groq.resources.chat.completions:

create(*, messages: 'Iterable[ChatCompletionMessageParam]', model: "Union[str, Literal['gemma2-9b-it', 'llama-3.3-70b-versatile', 'llama-3.1-8b-instant', 'llama-guard-3-8b', 'llama3-70b-8192', 'llama3-8b-8192']]", exclude_domains: 'Optional[List[str]] | NotGiven' = NOT_GIVEN, frequency_penalty: 'Optional[float] | NotGiven' = NOT_GIVEN, function_call: 'Optional[completion_create_params.FunctionCall] | NotGiven' = NOT_GIVEN, functions: 'Optional[Iterable[completion_create_params.Function]] | NotGiven' = NOT_GIVEN, include_domains: 'Optional[List[str]] | NotGiven' = NOT_GIVEN, logit_bias: 'Optional[Dict[str, int]] | NotGiven' = NOT_GIVEN, logprobs: 'Optional[bool] | NotGiven' = NOT_GIVEN, max_completion_tokens: 'Optional[int] | NotGiven' = NOT_GIVEN, max_tokens: 'Optional[int] | NotGiven' = NOT_GIVEN, metadata: 'Optional[Dict[str, str]] | NotGiven' = NOT_GIVEN, n: 'Optional[int] | NotGiven' = NOT_GIVEN, parallel_tool_calls: 'Optional[bool] | NotGiven' = NOT_GIVEN, presence_penalty: 'Optional[float] | NotGiven' = NOT_GIVEN, reasoning_effort: "Optional[Literal['none', 'default']] | NotGiven" = NOT_GIVEN, reasoning_format: "Optional[Literal['hidden', 'raw', 'parsed']] | NotGiven" = NOT_GIVEN, response_format: 'Optional[completion_create_params.ResponseFormat] | NotGiven' = NOT_GIVEN, search_settings: 'Optional[completion_create_params.SearchSettings] | NotGiven' = NOT_GIVEN, seed: 'Optional[int] | NotGiven' = NOT_GIVEN, service_tier: "Optional[Literal['auto', 'on_demand', 'flex']] | NotGiven" = NOT_GIVEN, stop: 'Union[Optional[str], List[str], None] | NotGiven' = NOT_GIVEN, store: 'Optional[bool] | NotGiven' = NOT_GIVEN, stream: 'Optional[Literal[False]] | Literal[True] | NotGiven' = NOT_GIVEN, temperature: 'Optional[float] | NotGiven' = NOT_GIVEN, tool_choice: 'Optional[ChatCompletionToolChoiceOptionParam] | NotGiven' = NOT_GIVEN, tools: 'Optional[Iterable[ChatCompletionToolParam]] | NotGiven' = NOT_GIVEN, top_logprobs: 'Optional[int] | NotGiven' = NOT_GIVEN, top_p: 'Optional[float] | NotGiven' = NOT_GIVEN, user: 'Optional[str] | NotGiven' = NOT_GIVEN, extra_headers: 'Headers | None' = None, extra_query: 'Query | None' = None, extra_body: 'Body | None' = None, timeout: 'float | httpx.Timeout | None | NotGiven' = NOT_GIVEN) -> 'ChatCompletion | Stream[ChatCompletionChunk]' method of groq.resources.chat.completions.Completions instance
    Creates a model response for the given chat conversation.

    Args:
      messages: A list of messages comprising the conversation so far.

      model: ID of the model to use. For details on which models are compatible with the Chat
          API, see available [models](https://console.groq.com/docs/models)

      exclude_domains: Deprecated: Use search_settings.exclude_domains instead. A list of domains to
          exclude from the search results when the model uses a web search tool.

      frequency_penalty: Number between -2.0 and 2.0. Positive values penalize new tokens based on their
          existing frequency in the text so far, decreasing the model's likelihood to
          repeat the same line verbatim.

      function_call: Deprecated in favor of `tool_choice`.

          Controls which (if any) function is called by the model. `none` means the model
          will not call a function and instead generates a message. `auto` means the model
          can pick between generating a message or calling a function. Specifying a
          particular function via `{"name": "my_function"}` forces the model to call that
          function.

          `none` is the default when no functions are present. `auto` is the default if
          functions are present.

      functions: Deprecated in favor of `tools`.

          A list of functions the model may generate JSON inputs for.

      include_domains: Deprecated: Use search_settings.include_domains instead. A list of domains to
          include in the search results when the model uses a web search tool.

      logit_bias: This is not yet supported by any of our models. Modify the likelihood of
          specified tokens appearing in the completion.

      logprobs: This is not yet supported by any of our models. Whether to return log
          probabilities of the output tokens or not. If true, returns the log
          probabilities of each output token returned in the `content` of `message`.

      max_completion_tokens: The maximum number of tokens that can be generated in the chat completion. The
          total length of input tokens and generated tokens is limited by the model's
          context length.

      max_tokens: Deprecated in favor of `max_completion_tokens`. The maximum number of tokens
          that can be generated in the chat completion. The total length of input tokens
          and generated tokens is limited by the model's context length.

      metadata: This parameter is not currently supported.

      n: How many chat completion choices to generate for each input message. Note that
          the current moment, only n=1 is supported. Other values will result in a 400
          response.

      parallel_tool_calls: Whether to enable parallel function calling during tool use.

      presence_penalty: Number between -2.0 and 2.0. Positive values penalize new tokens based on
          whether they appear in the text so far, increasing the model's likelihood to
          talk about new topics.

      reasoning_effort: this field is only available for qwen3 models. Set to 'none' to disable
          reasoning. Set to 'default' or null to let Qwen reason.

      reasoning_format: Specifies how to output reasoning tokens

      response_format: An object specifying the format that the model must output. Setting to
          `{ "type": "json_schema", "json_schema": {...} }` enables Structured Outputs
          which ensures the model will match your supplied JSON schema. json_schema
          response format is only supported on llama 4 models. Setting to
          `{ "type": "json_object" }` enables the older JSON mode, which ensures the
          message the model generates is valid JSON. Using `json_schema` is preferred for
          models that support it.

      search_settings: Settings for web search functionality when the model uses a web search tool.

      seed: If specified, our system will make a best effort to sample deterministically,
          such that repeated requests with the same `seed` and parameters should return
          the same result. Determinism is not guaranteed, and you should refer to the
          `system_fingerprint` response parameter to monitor changes in the backend.

      service_tier: The service tier to use for the request. Defaults to `on_demand`.

          - `auto` will automatically select the highest tier available within the rate
            limits of your organization.
          - `flex` uses the flex tier, which will succeed or fail quickly.

      stop: Up to 4 sequences where the API will stop generating further tokens. The
          returned text will not contain the stop sequence.

      store: This parameter is not currently supported.

      stream: If set, partial message deltas will be sent. Tokens will be sent as data-only
          [server-sent events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#Event_stream_format)
          as they become available, with the stream terminated by a `data: [DONE]`
          message. [Example code](/docs/text-chat#streaming-a-chat-completion).

      temperature: What sampling temperature to use, between 0 and 2. Higher values like 0.8 will
          make the output more random, while lower values like 0.2 will make it more
          focused and deterministic. We generally recommend altering this or top_p but not
          both.

      tool_choice: Controls which (if any) tool is called by the model. `none` means the model will
          not call any tool and instead generates a message. `auto` means the model can
          pick between generating a message or calling one or more tools. `required` means
          the model must call one or more tools. Specifying a particular tool via
          `{"type": "function", "function": {"name": "my_function"}}` forces the model to
          call that tool.

          `none` is the default when no tools are present. `auto` is the default if tools
          are present.

      tools: A list of tools the model may call. Currently, only functions are supported as a
          tool. Use this to provide a list of functions the model may generate JSON inputs
          for. A max of 128 functions are supported.

      top_logprobs: This is not yet supported by any of our models. An integer between 0 and 20
          specifying the number of most likely tokens to return at each token position,
          each with an associated log probability. `logprobs` must be set to `true` if
          this parameter is used.

      top_p: An alternative to sampling with temperature, called nucleus sampling, where the
          model considers the results of the tokens with top_p probability mass. So 0.1
          means only the tokens comprising the top 10% probability mass are considered. We
          generally recommend altering this or temperature but not both.

      user: A unique identifier representing your end-user, which can help us monitor and
          detect abuse.

      extra_headers: Send extra headers

      extra_query: Add additional query parameters to the request

      extra_body: Add additional JSON properties to the request

      timeout: Override the client-level default timeout for this request, in seconds

As a first example, note how the messages input is given as a list of a dictionaries with `role` and `content` keys. This is in a ChatML format recognised by many LLMs.

In [8]:
chat_completion = client.chat.completions.create(
    messages=[
        {   "role": "system", # sets the persona of the model
            "content": "You are a helpful assistant."
        },
        {
            "role": "user", # what the user wants the assistant to do
            "content": "Explain briefly how large language models work",
        }
    ],
    model="llama-3.3-70b-versatile",
)

print(chat_completion.choices[0].message.content)

Large language models are a type of artificial intelligence (AI) that process and understand human language. They work by:

1. **Training**: Being trained on vast amounts of text data, such as books, articles, and conversations.
2. **Pattern recognition**: Recognizing patterns and relationships in language, such as grammar, syntax, and semantics.
3. **Prediction**: Using these patterns to predict the next word or character in a sequence, based on context and probability.

When you ask a question or provide input, the model:

1. **Tokenizes**: Breaks down your input into individual words or tokens.
2. **Analyzes**: Analyzes the tokens to understand their meaning and context.
3. **Generates**: Generates a response based on the patterns and relationships learned during training.

This process allows large language models to generate human-like text, answer questions, and even engage in conversations.

The output is in Markdown format so the following line formats this text.

In [9]:
Markdown(chat_completion.choices[0].message.content)

Large language models are a type of artificial intelligence (AI) that process and understand human language. They work by:

1. **Training**: Being trained on vast amounts of text data, such as books, articles, and conversations.
2. **Pattern recognition**: Recognizing patterns and relationships in language, such as grammar, syntax, and semantics.
3. **Prediction**: Using these patterns to predict the next word or character in a sequence, based on context and probability.

When you ask a question or provide input, the model:

1. **Tokenizes**: Breaks down your input into individual words or tokens.
2. **Analyzes**: Analyzes the tokens to understand their meaning and context.
3. **Generates**: Generates a response based on the patterns and relationships learned during training.

This process allows large language models to generate human-like text, answer questions, and even engage in conversations.

## Text summarisation

We start with a llama3-8b-8192, a model using just over 8 billion parameters with at most 8192 tokens produced as output.

Here is an article to be summarised from the [cnn_dailymail](https://huggingface.co/datasets/cnn_dailymail) dataset:

In [10]:
story = """
SAN FRANCISCO, California (CNN) -- A magnitude 4.2 earthquake shook the San Francisco area Friday at 4:42 a.m. PT (7:42 a.m. ET), the U.S. Geological Survey reported. The quake left about 2,000 customers without power, said David Eisenhower, a spokesman for Pacific Gas and Light. Under the USGS classification, a magnitude 4.2 earthquake is considered "light," which it says usually causes minimal damage. "We had quite a spike in calls, mostly calls of inquiry, none of any injury, none of any damage that was reported," said Capt. Al Casciato of the San Francisco police. "It was fairly mild." Watch police describe concerned calls immediately after the quake » . The quake was centered about two miles east-northeast of Oakland, at a depth of 3.6 miles, the USGS said. Oakland is just east of San Francisco, across San Francisco Bay. An Oakland police dispatcher told CNN the quake set off alarms at people's homes. The shaking lasted about 50 seconds, said CNN meteorologist Chad Myers. According to the USGS, magnitude 4.2 quakes are felt indoors and may break dishes and windows and overturn unstable objects. Pendulum clocks may stop.
"""

**Exercise:**
Summarise the story text using the following three prompts. Use the format given above but here there is no need to set the persona (i.e. only include one dictionary in the messages list when calling `client.chat.completions.create`.) Comment on any differences.

1) "Summarise the following article in 3 sentences."

2) "Give me a TL;DR of this text."

3) "What's the key takeaway here?"

In [13]:
prompts = ["Summarise the following article in 3 sentences. ", "Give me a TL;DR of this text. ", "What's the key takeaway here?"]
#content will be p + story for p in prompts
def get_summary(prompt):
    completion = client.chat.completions.create(
        messages=[{
            "role": "user",
            "content": f"{prompt}\n\n{story}"
        }],
        model="llama3-8b-8192",
        max_tokens=512,
        temperature=0.2
    )
    return completion.choices[0].message.content.strip()

# 1. Summarise in 3 sentences
summary_3_sentences = get_summary("Summarise the following article in 3 sentences.")

# 2. TL;DR
summary_tldr = get_summary("Give me a TL;DR of this text.")

# 3. Key takeaway
summary_takeaway = get_summary("What's the key takeaway here?")

# Display all results
print("=== Summary (3 Sentences) ===")
print(summary_3_sentences)
print("\n=== TL;DR ===")
print(summary_tldr)
print("\n=== Key Takeaway ===")
print(summary_takeaway)
# ANSWER

=== Summary (3 Sentences) ===
Here is a summary of the article in 3 sentences:

A magnitude 4.2 earthquake struck the San Francisco area at 4:42 a.m. PT on Friday, causing minimal damage and no reported injuries. The quake left around 2,000 customers without power, but authorities reported no significant damage or injuries. The earthquake was centered about two miles east-northeast of Oakland and was felt for about 50 seconds, causing some alarm and concern among residents.

=== TL;DR ===
A 4.2 magnitude earthquake struck the San Francisco area at 4:42am, causing about 2,000 power outages but no reported injuries or significant damage. The quake was centered near Oakland and lasted about 50 seconds, with some residents reporting alarms going off at their homes.

=== Key Takeaway ===
The key takeaway is that a magnitude 4.2 earthquake struck the San Francisco area, causing minimal damage and no reported injuries, but leaving about 2,000 customers without power.

Run the above code again below and note that the answers may differ. This is due to the probabilistic nature of LLM token generation.

In [14]:
# ANSWER
def get_summary(prompt):
    completion = client.chat.completions.create(
        messages=[{
            "role": "user",
            "content": f"{prompt}\n\n{story}"
        }],
        model="llama3-8b-8192",
        max_tokens=512,
        temperature=0.2
    )
    return completion.choices[0].message.content.strip()

# 1. Summarise in 3 sentences
summary_3_sentences = get_summary("Summarise the following article in 3 sentences.")

# 2. TL;DR
summary_tldr = get_summary("Give me a TL;DR of this text.")

# 3. Key takeaway
summary_takeaway = get_summary("What's the key takeaway here?")

# Display all results
print("=== Summary (3 Sentences) ===")
print(summary_3_sentences)
print("\n=== TL;DR ===")
print(summary_tldr)
print("\n=== Key Takeaway ===")
print(summary_takeaway)

=== Summary (3 Sentences) ===
Here is a summary of the article in 3 sentences:

A magnitude 4.2 earthquake struck the San Francisco area at 4:42 a.m. PT on Friday, causing minimal damage and leaving about 2,000 customers without power. The quake was considered "light" by the USGS and was felt indoors, with reports of alarms going off at homes and some minor disruptions. The shaking lasted about 50 seconds and no injuries or significant damage were reported, with authorities describing the quake as "fairly mild".

=== TL;DR ===
A magnitude 4.2 earthquake struck the San Francisco area at 4:42am, causing minimal damage and no reported injuries. The quake was centered near Oakland and left around 2,000 customers without power.

=== Key Takeaway ===
The key takeaway is that a magnitude 4.2 earthquake struck the San Francisco area, causing minimal damage and no reported injuries, but did leave around 2,000 customers without power.

## Text completion

**Exercise**: In this section adjust the `max_completion_tokens` and `temperature` settings below to obtain different responses. Show some examples with the prompt "Continue the story: It was a great time to be alive" with the model "llama-3.1-8b-instant".

* max_completion_tokens - the maximum number of tokens to generate. Note that longer words are made of multiple tokens (set to 200 and 500)
* temperature (positive number) - the higher the number the more random (creative) the output (set to 0.2, 0.8, 2)

In [16]:
# ANSWER (set max_completion_tokens=200, do not have a temperature setting)
def complete_story(prompt, max_tokens=None, temperature=None):
    params = {
        "messages": [{"role": "user", "content": prompt}],
        "model": "llama-3.1-8b-instant"
    }

    # Add optional params if provided
    if max_tokens is not None:
        params["max_tokens"] = max_tokens
    if temperature is not None:
        params["temperature"] = temperature

    response = client.chat.completions.create(**params)
    return response.choices[0].message.content.strip()
print(complete_story("Continue the story: It was a great time to be alive", max_tokens=200))

It was a great time to be alive, with music filling the streets and laughter echoing off the buildings. The sun was shining, casting a warm glow over the bustling city. People of all ages and backgrounds seemed to be enjoying themselves, whether it was a group of teenagers playing a lively game of street hockey or a couple strolling hand in hand through the park.

As I made my way through the crowds, I couldn't help but feel a sense of excitement and possibility. Everywhere I looked, there were reminders that this was a time of great change and progress. New technologies were emerging, new ideas were being explored, and people were pushing the boundaries of what was thought possible.

I stopped to watch a group of artists performing on a street corner. They were a eclectic mix of musicians, dancers, and visual artists, each one bringing their own unique style and energy to the performance. The music was infectious, and soon the crowd was dancing and singing along.

As I watched, a young woman caught

In [17]:
# ANSWER (set max_completion_tokens=500, do not have a temperature setting)
print(complete_story("Continue the story: It was a great time to be alive", max_tokens=500))

It was a great time to be alive, and for Jack, that sentiment couldn't have been more true. The year was 1967, and the world was bursting with creativity and change. Music blasted from every corner, from the Beatles' psychedelic melodies to the soulful cries of Aretha Franklin. The Summer of Love was in full swing, and cities like San Francisco and New York were magnets for young people seeking freedom, self-expression, and a sense of belonging.

As a free-spirited artist, Jack felt like he was exactly where he was meant to be. He spent his days painting vibrant murals, experimenting with music, and hanging out with a diverse group of friends who shared his passion for life.

One sunny afternoon, Jack strolled down Haight-Ashbury, the epicenter of San Francisco's counterculture. He passed by the iconic Fillmore, where Janis Joplin and Jimi Hendrix were about to take the stage. The air vibrated with anticipation, and the scent of incense and patchouli wafted from the crowds gathered outside.

As Jack wandered through the neighborhood, he stumbled upon a small, eclectic shop called "The Cosmic Cat." The store's window display caught his eye – a mesmerizing arrangement of crystals, tarot cards, and hand-painted ceramics. Jack couldn't resist the urge to venture inside.

The shop was a treasure trove of bohemian delights, and Jack felt an instant connection to the owner, a wise and gentle woman named Luna. She welcomed him with a warm smile, and as they chatted, Jack found himself drawn to the mysteries of the universe and the power of the human spirit.

Luna sensed Jack's curiosity and invited him to explore the shop further. Together, they delved into the realm of astrology, mysticism, and the mysteries of the cosmos. Jack's mind expanded as he listened to Luna's stories of ancient wisdom and modern spirituality.

As the afternoon sun began to set, Jack realized he had been lost in conversation for hours. He reluctantly bid Luna farewell, promising to return soon. As he stepped out of the shop, he felt a sense of purpose and belonging that he had never experienced before. The world seemed like a vast and wondrous tapestry, full of hidden patterns and secrets waiting to be uncovered.

For Jack, the Summer of Love had just begun – a season of self-discovery, creative exploration, and spiritual growth that would forever shape

In [18]:
# ANSWER (set temperature = 0.2, do not have a max_completion_tokens setting)
print(complete_story("Continue the story: It was a great time to be alive", temperature=0.2))

It was a great time to be alive, and Emily couldn't help but feel a sense of excitement and wonder as she walked through the bustling streets of the city. The year was 2050, and the world was a vastly different place from the one her grandparents had grown up in. Technology had advanced at an exponential rate, and the once-distant dreams of science fiction had become a reality.

As she strolled through the crowded market, Emily's eyes were drawn to the towering skyscrapers that seemed to stretch up to the sky. The buildings were covered in a latticework of holographic advertisements, flashing and pulsing with a kaleidoscope of colors that seemed to dance in the air.

She passed by a group of people huddled around a small, sleek device that was projecting a 3D image of a virtual reality world. The scene was so realistic that Emily could almost smell the virtual coffee and feel the virtual breeze on her skin.

As she continued on her way, Emily noticed a group of people gathered around a street performer who was juggling a trio of levitating orbs. The orbs were made of a lightweight, transparent material that seemed to defy gravity, and the performer was expertly manipulating them with a series of precise hand movements.

Emily watched in awe as the performer began to incorporate a series of complex mathematical equations into his routine, using the orbs to illustrate the concepts in a way that was both beautiful and mesmerizing.

As she continued to watch, Emily felt a tap on her shoulder. It was her friend, Rachel, who was grinning from ear to ear.

"Hey, Em, have you seen this?" Rachel asked, nodding towards the performer.

Emily shook her head, and Rachel pulled out a small device from her pocket. "I've been tracking the performer's movements," she explained, "and I think I've figured out the underlying math behind his routine."

Emily's eyes widened as Rachel began to explain the complex equations that governed the performer's movements. It was a beautiful example of how art and science could intersect, and Emily felt a sense of wonder at the incredible possibilities that the world had to offer.

As they continued to watch the performer, Emily couldn't help but feel grateful to be alive in this incredible time. The world was full of wonder and discovery, and she felt privileged to be a part of it.

But as she looked around at the crowds of people, Emily couldn't help but feel a sense of unease. There were so many people, all rushing to get somewhere, all chasing after their own individual goals and desires. It was a world that was increasingly fast-paced and competitive, and Emily couldn't help but wonder if anyone was truly happy.

As she turned to Rachel, Emily asked, "Do you ever feel like we're just going through the motions, like we're just trying to keep up with the pace of the world?"

Rachel nodded thoughtfully, her eyes scanning the crowd. "I do," she said. "But I think that's just part of the human experience. We're always searching for something more, something better. And I think that's what makes life so interesting."

Emily nodded, feeling a sense of understanding wash over her. Maybe this was the key to happiness, she thought - not the destination, but the journey itself. The search for something more, the pursuit of knowledge and wonder.

As they continued to watch the performer, Emily felt a sense of peace settle over her. It was a great time to be alive, and she was grateful to be a part of it.

In [19]:
# ANSWER (set temperature = 1, do not have a max_completion_tokens setting)
print(complete_story("Continue the story: It was a great time to be alive", temperature=1))

It was a great time to be alive, especially for Emily. Summer had finally arrived in the small town of Oakdale, and the warm sunshine and long days seemed to bring everyone together. The smell of freshly cut grass and blooming flowers filled the air, and the sound of laughter and children's shouts echoed through the streets.

Emily, a bright-eyed and adventurous 20-year-old, was soaking up every moment of it. She had just finished her second year of college and was enjoying a well-deserved break. She had spent the morning lounging in the park, reading a book and soaking up the sun's warm rays. Now, she was walking home, feeling carefree and content.

As she strolled down the main street of Oakdale, Emily noticed a group of friends gathered outside the local diner. They were sipping on milkshakes and laughing together, and Emily couldn't help but feel a pang of envy. She wished she could join them, but she was running a bit late for her shift at the ice cream parlor.

With a quick wave to her friends, Emily continued on her way home. She lived in a cozy apartment above her family's bakery, where the smell of freshly baked bread and pastries wafted up through the vents. As she climbed the stairs, Emily felt a sense of comfort and familiarity wash over her. She loved her family's bakery, and the way it seemed to be the heart of the community.

Just as Emily was about to open the door to her apartment, her phone buzzed with a text from her best friend, Rachel. "Hey girl, where are you? I'm so bored and I need your help ASAP!" Rachel was always getting into some kind of trouble, and Emily was happy to oblige.

With a smile on her face, Emily tossed her bag onto the couch and grabbed her keys. "Where do you need me?" she typed back to Rachel.

Little did Emily know, her carefree day was about to take an unexpected turn...

Note what happens when the temperature is set too high!

In [20]:
# ANSWER (set temperature = 2, do not have a max_completion_tokens setting)
print(complete_story("Continue the story: It was a great time to be alive", temperature=2))

As I looked out my sun-speckled window, watching the sunlight dance across the streets below, I couldn't help but feel an overwhelming sense of enthusiasm for life. The city was alive – it hummed, pulsed, and beat with an energy all its own.

The sounds were endless – chatter, beeping horns, the clinking of coffee against paper cups rising up like sweet jazz riffs into the cool, fresh morning air. My heart lifted as the city began waking up around me. People were smiling – genuine smiles – not just smiles hiding tired exhaustion like I often see people wearing on the weekdays; no this was happiness unadulerated pure pure love in the fresh morning dew. And I know why

My family was coming over to the tiny diner down by Park street to try a taste of my cousin’s latest invention an all-mushroom breakfast pizza that everyone had told they couldn's miss at the weekend markets. It wasn't about the meal that awaited us at this small place with walls painted by some aspiring artist; it certainly was the atmosphere, it was a feeling in the very pores of my veins - an optimism and pure pure life, the way we had grown so much but still remained the same as a loving, warm and vibrant family with love flowing deep with each new day we meet to savor the morning over some of the most fantastic home made pizzas anyone has yet ever had.

But that's not all I remember walking with mom to my school – it used to take about fifteen to twenty long wind filled happy moments of watching street performers who came and entertained with beautiful acts and magic for every age as if you are walking inside a wonderland - where nothing is but pure wonder. They used a mixture of art music laughter joy in the very fabric, weaving an enchanting melody so that no single child and even the older could take their gaze of it; I remember walking and smiling and smiling and feeling my little soul filled to the maximum that morning – all my friends who lived just by my house, their excitement echoed by mine, and so many children with faces filled by an inexpressable grin were there and there as we were on the edge.

My dad still recalls it – a time when everyone felt alive with possibilities when you knew nothing and nothing scared or hurt you. There would not always exist another like it and it felt that you're on the precipice - about to dive into some vast unchartered waters. The world looked new; our imagination painted with fresh bright strokes like the ones an infant holds for first painting the picture and yet we did feel something special and that something - the excitement and thrill and the endless promise to chase dreams no matter the world threw our way kept alive the love - and all the memories and this feeling we held inside – we still shared this secret smile even to now – in our eyes when we spoke about this time - 'that time, It was a great time to be alive.'

### Zero-shot and one-short prompting for question-answering

This section shows the impact of prompting on the response. Zero-shot prompting means we provide the prompt without any examples or additional context. Let us initially ask Mistral a question using no prompting.

In [21]:
response = client.chat.completions.create(
    model="llama-3.1-8b-instant",
    messages=[{"role": "user", "content": "How do two chemicals react?"}],
    temperature = 0.8,
)

Markdown(response.choices[0].message.content)

Chemical reactions between two substances occur when there's a change in their chemical bonds, resulting in the formation of new substances. Let's break down the process:

1. **Chemical Energy**: Two chemicals (reactants) come into contact with each other. This interaction can be triggered by various factors, such as heat, light, or the presence of a catalyst.
2. **Bond Breaking**: The molecules of the reactants vibrate and collide with each other. When they collide, their chemical bonds break, releasing energy.
3. **Bond Forming**: The broken bonds from the reactants are rearranged to form new bonds with other reactants, resulting in the formation of new products.
4. **Energy Release or Absorption**: Chemical reactions often involve the release or absorption of energy, which can be in the form of heat, light, or sound.

**Types of Chemical Reactions**:

1. **Synthesis Reaction**: Two or more reactants combine to form a new compound (e.g., hydrogen + oxygen → water).
2. **Decomposition Reaction**: A single reactant breaks down into two or more products (e.g., water → hydrogen + oxygen).
3. **Single-Displacement Reaction**: One element displaces another element from a compound (e.g., zinc + copper sulfate → zinc sulfate + copper).
4. **Double-Displacement Reaction**: Two compounds exchange partners to form new products (e.g., sodium chloride + silver nitrate → sodium nitrate + silver chloride).

**Factors Affecting Chemical Reactions**:

1. **Concentration**: Higher concentrations can increase reaction rates.
2. **Temperature**: Higher temperatures can increase reaction rates, but excessive heat can slow or stop reactions.
3. **Pressure**: Increased pressure can increase reaction rates, but it depends on the reaction.
4. **Catalysts**: Substances that speed up reactions without being consumed by them.
5. **Surface Area**: Increasing surface area can increase reaction rates.

**Notable Examples**:

1. **Combustion Reaction**: Burning wood or gasoline releases energy (e.g., wood + oxygen → carbon dioxide + water + heat).
2. **Acid-Base Reaction**: Mixing acid and base produces a salt and water (e.g., hydrochloric acid + sodium hydroxide → sodium chloride + water).

Keep in mind that this is a simplified explanation. Chemical reactions can be complex, and factors like entropy and equilibrium can influence the outcome.

Do you have a specific reaction or topic you'd like me to explore further?

**Exercise:** Ask the same question but modify the prompt to return the answer to the same question in a simpler form (still using the llama-3.1-8b-instant model). Experiment with different prompts.

In [22]:
# ANSWER
response = client.chat.completions.create(
    model="llama-3.1-8b-instant",
    messages=[{"role": "user", "content": "Explain how two chemicals react in simple words a 10-year-old could understand."}],
    temperature=0.8,
)
Markdown(response.choices[0].message.content)

Let's say we have two chemicals: Soda and Baking Soda.

When we mix these two chemicals together, we get a fun reaction. Here's what happens:

1. Soda is a type of liquid that's full of tiny particles called atoms.
2. Baking Soda is a type of powder that's also made of tiny particles called atoms.
3. When we mix the Soda and Baking Soda together, the tiny particles start to get excited and move around really fast.
4. As they move around, they start to rub against each other and make a new substance called Carbon Dioxide.
5. The Carbon Dioxide is a gas that gets released into the air as bubbles.
6. When we see the bubbles rising up, it's because the Carbon Dioxide is trying to get out of the mixture.

So, in simple words, when we mix Soda and Baking Soda, they create a reaction that makes bubbles. This reaction is fun to see and hear, and it's a great example of how chemicals can interact with each other.

Here's a simple equation that represents this reaction:

Soda (Hydrogen peroxide) + Baking Soda (Sodium bicarbonate) → Carbon Dioxide (CO2) + Water (H2O)

In [24]:
response = client.chat.completions.create(
    model="llama-3.1-8b-instant",
    messages=[{"role": "user", "content": "Give a short and simple explanation of how two chemicals react."}],
    temperature=0.8,
)
Markdown(response.choices[0].message.content)

Let's consider a simple example of a chemical reaction between hydrogen gas (H2) and oxygen gas (O2) to form water (H2O).

**Reaction:**

2H2 (hydrogen gas) + O2 (oxygen gas) → 2H2O (water)

**Explanation:**

1. The hydrogen and oxygen molecules collide with each other.
2. The oxygen molecule (O2) breaks apart into individual oxygen atoms.
3. The hydrogen molecules (H2) break apart into individual hydrogen atoms.
4. The hydrogen and oxygen atoms combine to form water molecules (H2O).

This reaction is an example of a combustion reaction, where two different elements combine to form a new compound.

In [25]:
response = client.chat.completions.create(
    model="llama-3.1-8b-instant",
    messages=[{"role": "user", "content": "How do two chemicals react? Use a food or cooking example to explain."}],
    temperature=0.8,
)
Markdown(response.choices[0].message.content)

Let's consider a common example from cooking to explain how two chemicals react. A chemical reaction occurs when two or more substances interact to form new substances.

**Example: Rancid Butter and Baking Soda**

Imagine you're making cookies and you add a pinch of baking soda (sodium bicarbonate) to the dough. The baking soda reacts with the acidic properties in the butter (lactic acid) to produce carbon dioxide gas.

The chemical reaction is:

Sodium bicarbonate (NaHCO3) + Lactic acid (CH3CH(OH)COOH) → Carbon dioxide (CO2) + Water (H2O) + Salt (NaCH3CH(OH)COO)

In this reaction, the baking soda (sodium bicarbonate) reacts with the lactic acid in the butter to form carbon dioxide gas, which gets trapped in the dough, making it rise. This reaction is a classic example of an acid-base reaction, where the acid in the butter reacts with the base in the baking soda to form a new compound.

**What's happening at a molecular level?**

When the baking soda comes into contact with the lactic acid in the butter, the sodium and hydrogen ions in the baking soda transfer to the lactic acid molecules. This transfer of ions causes the molecules to break apart, releasing carbon dioxide gas as a byproduct. The carbon dioxide gets trapped in the dough, causing it to rise.

**Key takeaways:**

1. Chemical reactions occur when two or more substances interact to form new substances.
2. Acid-base reactions involve the transfer of ions between molecules, resulting in the formation of new compounds.
3. The reaction between baking soda and lactic acid in butter is a classic example of an acid-base reaction, producing carbon dioxide gas and causing the dough to rise.

I hope this example helps illustrate how two chemicals react!

### One-shot prompting ###

Next, note the dramatic change when we give the following template setting a new role and providing an English question followed by a French translation.

In [26]:
response = client.chat.completions.create(
    model="llama-3.1-8b-instant",
    messages=[{"role": "system",
             "content": "You translate English to French."},
              {"role": "user",
               "content": "What time is it?"},
               {"role": "assistant",
               "content": "Quelle heure est-il?"},
              {"role": "user",
               "content": "How do two chemicals react?"}],
    temperature = 0.8,
)
print(response.choices[0].message.content)

Comment deux produits chimiques réagissent-ils?

### Few-shot prompting

Recall that since the text generation process outputs one token at a time, their outputs often need adjusting. This is where examples can help.

In [27]:
prompt1 = "I'm gonna head out now, see you later."
response1 = "I will be leaving now. See you later."

prompt2 =  "That movie was super cool!"
response2 = "The movie was very impressive."

prompt3 = "Can't make it to the meeting, sorry."


response = client.chat.completions.create(
    model="llama3-70b-8192",
    messages=[
        {"role": "system", "content": "You are a professional editor. Rewrite casual sentences into a formal tone."},
        {"role": "user", "content": prompt1},
        {"role": "assistant", "content": response1},
        {"role": "user", "content": prompt2},
        {"role": "assistant", "content": response2},
        {"role": "user", "content": prompt3},
    ]
)

print(response.choices[0].message.content.strip())

Regrettably, I will be unable to attend the meeting. My apologies.

The output can also be moulded to provide SQL output.

In [28]:
prompt1 = "Show me all users who signed up in the last 30 days."
response1 = "SELECT * FROM users WHERE signup_date >= CURRENT_DATE - INTERVAL '30 days';"

prompt2 = "What is the average order value?"
response2 =  "SELECT AVG(order_total) FROM orders;"

prompt3 = "List products that are out of stock."

response = client.chat.completions.create(
    model="llama3-70b-8192",
    messages=[
        {"role": "system", "content": "You are an assistant that translates natural language to SQL."},
        {"role": "user", "content": prompt1},
        {"role": "assistant", "content": response1},
        {"role": "user", "content": prompt2},
        {"role": "assistant", "content": response2},
        {"role": "user", "content": prompt3},
    ]
)

print(response.choices[0].message.content.strip())

SELECT * FROM products WHERE quantity_in_stock = 0;

**Exercise**: Create a few examples to train the "llama3-70b-8192" LLM to take in user content in the form below and provide output as a pandas dataframe. Use the `exec` function to execute its output to display the answer of sample input as a data frame.

Example:

given the user content

"""

| col1 | col2 | col3

| 32 | 27 | 25

| 64 | 23 | 14

"""

train the model to output

df = pd.DataFrame({'col1': [32, 64], 'col2': [27, 23], 'col3': [25, 14]})

In [30]:
#ANSWER
prompt_example = """
You are a Python assistant. Convert tabular text input into a pandas DataFrame definition.

Input:
| name | age | city |
| John | 30  | NYC  |
| Lisa | 25  | LA   |

Output:
df = pd.DataFrame({'name': ['John', 'Lisa'], 'age': [30, 25], 'city': ['NYC', 'LA']})
"""

# New user content to test
user_input = """
| col1 | col2 | col3 |
| 32   | 27   | 25   |
| 64   | 23   | 14   |
"""

response = client.chat.completions.create(
    model="llama3-70b-8192",
    messages=[
        {"role": "system", "content": "You are a Python assistant that converts tables to pandas DataFrames."},
        {"role": "user", "content": prompt_example},
        {"role": "assistant", "content": "df = pd.DataFrame({'name': ['John', 'Lisa'], 'age': [30, 25], 'city': ['NYC', 'LA']})"},
        {"role": "user", "content": user_input}
    ],
    temperature=0.2
)

generated_code = response.choices[0].message.content.strip()
print("Generated code:\n", generated_code)

exec(generated_code)
display(df)

Generated code:
 df = pd.DataFrame({'col1': [32, 64], 'col2': [27, 23], 'col3': [25, 14]})

   col1  col2  col3
0    32    27    25
1    64    23    14

Also show what happens when the question is asked in the absence of a system role and without few-shot prompting.

In [31]:
# ANSWER
user_input = """
| col1 | col2 | col3 |
| 32   | 27   | 25   |
| 64   | 23   | 14   |
"""

response = client.chat.completions.create(
    model="llama3-70b-8192",
    messages=[
        {"role": "user", "content": f"Convert this to a pandas dataframe:\n{user_input}"}
    ],
    temperature=0.2
)

print(response.choices[0].message.content.strip())

Here is the equivalent pandas DataFrame:
```
import pandas as pd

data = {'col1': [32, 64], 'col2': [27, 23], 'col3': [25, 14]}
df = pd.DataFrame(data)

print(df)
```
Output:
```
   col1  col2  col3
0    32    27    25
1    64    23    14
```
Let me know if you have any questions!

### Chain-of-thought prompting

The results of question-answering can also be improved by prompting the LLM to provide intermediate steps.

**Exercise**: Using the following prompts, compare the answers of the "llama3-8b-8192" model (set seed=21). (If this model is no longer available choose a model with relatively few parameters.)

zero_shot_prompt = "How many s's are in the word 'success'?"

chain_of_thought_prompt = "How many s's are in the word 'success'? Explain your answer step by step by going through each letter in turn."

In [32]:
# ANSWER
zero_shot_prompt = "How many s's are in the word 'success'?"
chain_of_thought_prompt = "How many s's are in the word 'success'? Explain your answer step by step by going through each letter in turn."
response_zero_shot = client.chat.completions.create(
    model="llama3-8b-8192",
    messages=[{"role": "user", "content": zero_shot_prompt}],
    seed=21,
    temperature=0.2
)

print("Zero-shot response:\n", response_zero_shot.choices[0].message.content.strip())

Zero-shot response:
 There are 2 s's in the word "success".

In [33]:
response_cot = client.chat.completions.create(
    model="llama3-8b-8192",
    messages=[{"role": "user", "content": chain_of_thought_prompt}],
    seed=21,
    temperature=0.2
)

print("Chain-of-thought response:\n", response_cot.choices[0].message.content.strip())

Chain-of-thought response:
 Let's go through each letter in the word "success" to count the number of s's:

1. S - (first letter)
2. U - (second letter)
3. C - (third letter)
4. C - (fourth letter)
5. E - (fifth letter)
6. S - (sixth letter)
7. S - (seventh letter)

As we go through each letter, we can see that there are two S's in the word "success".

## Comparison of LLMs

**Exercise**: Compare the performance of 2 LLMs by outputting the answers of the following questions into a dataframe.

    "Tell me a joke about data science.",
    "How can one calculate 22 * 13 mentally?",
    "Write a creative story about a baby learning to crawl.",

Column headings:

Model Name | Question | Answer

In [34]:
pd.set_option('display.max_colwidth', None) # allows wide dataframes to be viewed
models = ["gemma2-9b-it", "llama-3.1-8b-instant"] #can edit this

# Questions to ask
questions = [
    "Tell me a joke about data science.",
    "How can one calculate 22 * 13 mentally?",
    "Write a creative story about a baby learning to crawl."
]

# Store results
results = []

# Query each model for each question
for model in models:
    for question in questions:
        response = client.chat.completions.create(
            model=model,
            messages=[{"role": "user", "content": question}],
            temperature=0.7  # A bit of creativity but not too wild
        )
        answer = response.choices[0].message.content.strip()
        results.append({
            "Model Name": model,
            "Question": question,
            "Answer": answer
        })

# Convert to DataFrame
df_results = pd.DataFrame(results)

# Show result
df_results

,Model Name,Question,Answer
0,gemma2-9b-it,Tell me a joke about data science.,Why did the data scientist break up with the statistician? \n\nBecause they had too many p-values and not enough real-world impact! 😂 \n\n\nLet me know if you'd like to hear another one! 😄
1,gemma2-9b-it,How can one calculate 22 * 13 mentally?,"Here's a way to calculate 22 * 13 mentally:\n\n**1. Break it down:**\n\n* Think of 22 as (20 + 2).\n\n**2. Distribute:**\n\n* Now you have (20 + 2) * 13 \n* Multiply 20 by 13: 20 * 13 = 260\n* Multiply 2 by 13: 2 * 13 = 26\n\n**3. Add the results:**\n\n* 260 + 26 = 286\n\n\n**Therefore, 22 * 13 = 286**"
2,gemma2-9b-it,Write a creative story about a baby learning to crawl.,"Bartholomew Buckleberry III, a cherub-cheeked infant with a shock of ginger hair, surveyed his kingdom. It was a vast expanse of plush carpet, striped with the fearsome shadows of toy giraffes and a rogue, purple dinosaur. The world was a thrilling, mysterious place, but Bartholomew was hopelessly stranded. He longed to explore, to conquer the mountainous pillows and the treacherous gap between his crib and the soft, beckoning rug.\n\nHe had watched, with envious eyes, his big sister, Penelope, navigate this terrain with ease. She'd zoom across the room like a furry comet, leaving a trail of scattered toys in her wake. Bartholomew wanted to be just like Penelope. He wanted to rumble, to roll, to conquer!\n\nOne afternoon, Bartholomew felt a surge of determination. He stretched his chubby arms, wiggling his fingers like nascent claws. He pushed with his legs, his tiny fists clenching and unclenching on the plush carpet. He wobbled, he teetered, he almost toppled over, but he didn't give up.\n\nSuddenly, a sensation of movement, of momentum, took over. Bartholomew was... crawling! He propelled himself forward with a jerky, uneven motion, his face scrunched in concentration. He felt a thrill of triumph as he reached the edge of his crib, then another as he crossed the perilous gap.\n\nThe world exploded in a cacophony of colors and textures. Bartholomew reached out a chubby hand, his fingers brushing against the plush fur of the giraffe. He giggled, a sound like a tiny wind chime, and pulled himself closer to the towering beast.\n\nThe giraffe, once a menacing shadow, now became a plaything. Bartholomew grabbed its long neck, rocking it back and forth, his contented smile widening. He had conquered the unknown, he had navigated the treacherous landscape, and he had discovered a whole new world of adventure.\n\nFrom that day on, Bartholomew Buckleberry III was a changed baby. He crawled with newfound confidence, his tiny body a blur of motion across the room. He wasn't just Bartholomew the baby anymore. He was Bartholomew the Explorer, the Conqueror, the Crawling King. And his kingdom, once a place of limitations, now stretched before him, ripe for the taking."
3,llama-3.1-8b-instant,Tell me a joke about data science.,Why did the data scientist quit his job?\n\nBecause he couldn't visualize a future in the company.
4,llama-3.1-8b-instant,How can one calculate 22 * 13 mentally?,"To calculate 22 * 13 mentally, you can use the following method:\n\n1. Break down the multiplication into easier parts: \n22 * 13 can be rewritten as (20 + 2) * 13.\n\n2. Multiply 20 and 13: \n20 * 13 = 260\n\n3. Multiply 2 and 13: \n2 * 13 = 26\n\n4. Add the results from step 2 and step 3: \n260 + 26 = 286\n\nTherefore, 22 * 13 equals 286."
5,llama-3.1-8b-instant,Write a creative story about a baby learning to crawl.,"**The Great Crawling Adventure**\n\nLily was a little ball of curiosity, with a mop of soft brown hair and a smile that could light up a room. At six months old, she was bursting with energy and a desire to explore the world around her. Her mom, Emma, had been patiently waiting for this moment – the moment when Lily would finally learn to crawl.\n\nOne sunny morning, Emma placed Lily on her tummy on the soft carpet of their living room. ""Go get it, baby girl!"" she encouraged, placing a toy just out of reach. Lily's eyes widened as she gazed at the toy, her little hands grasping and releasing as she tried to make sense of the world.\n\nAt first, Lily's attempts at crawling were more like wiggling and squirming. Her arms flailed about, and her legs kicked in all directions, but she didn't quite get the hang of it. Emma chuckled and cheered her on, ""You got this, Lily!"" She offered a helping hand, but Lily was determined to do it on her own.\n\nAs the days went by, Lily's efforts became more focused. She began to rock back and forth, using her arms to push herself forward. Emma placed toys just a little farther away, encouraging Lily to keep trying. And then, one magical moment, it happened.\n\nLily's hands grasped the carpet, and she slowly began to move forward, her legs pushing against the floor. It was a tiny, wobbly movement, but it was crawling! Emma squealed with delight, ""Lily, you're crawling! Oh, my baby is crawling!""\n\nLily's face lit up with a beaming smile as she continued to crawl across the room. She was so proud of herself, and Emma was right behind her, cheering her on. As they reached the toy, Lily grasped it in her little hands and gazed triumphantly at her mom.\n\nThe next few days were a flurry of crawling activity. Lily devoured every inch of their living room, exploring every nook and cranny. She crawled under the couch, behind the chairs, and even tried to climb up the curtains (much to Emma's dismay!). But with every attempt, Lily grew more confident, more determined.\n\nAs the weeks went by, Lily's crawling skills improved dramatically. She began to move across the room with ease, her little body gliding across the floor with a newfound sense of purpose. Emma watched with pride, snapping photos and videos to capture this special moment in time.\n\nAnd when Lily finally reached the door, she looked up at Emma with a mischievous grin, as if to say, ""You know what's next, don't you?"" Emma smiled back, knowing that the next great adventure was just around the corner.\n\nFor now, though, they would savor this moment – the moment when Lily learned to crawl, and the world became a vast, exciting playground, full of possibility and wonder."

### Bonus

See if you can prompt an LLM to perform sentiment analysis (output 'Positive' or 'Negative' only) on a given piece of text.

In [35]:
# ANSWER
text = "I absolutely love how easy this software is to use!"

prompt = f"""
Classify the sentiment of the following review as either Positive or Negative.
Only respond with 'Positive' or 'Negative'.

Review: "{text}"
Sentiment:
"""

response = client.chat.completions.create(
    model="llama-3.1-8b-instant",
    messages=[{"role": "user", "content": prompt}],
    temperature=0.0,  # Low temperature to reduce randomness
)

sentiment = response.choices[0].message.content.strip()
print("Predicted Sentiment:", sentiment)

Predicted Sentiment: Positive

## Conclusion

We worked with a few Large Language Models (LLMs) using Groq and experimented with prompting for summarisation, text completion and question-answering tasks.

We also explored controlling the randomness (creativity) of output through the temperature setting and tried different types of prompting to achieve desired forms of output.

## References
1. [Groq's prompting guide](https://console.groq.com/docs/prompting)
2. [Groq's playground](https://console.groq.com/playground)



---



---



> > > > > > > > > © 2025 Institute of Data


---



---